### ISSUE TITLE
Tabla de nationals

### ISSUE THREAD

**Issue by jaasielmalagon** [jaasielmalagon/TpEmpresarialFront#8]
En building blocks -> conectividad -> Tabla de nationals y surveillance
1. Debe ser clickable 
2. Debe cambiar la tabla de precios a su derecha
3. El background de video-surveillance debe ser transparente
4. Los precios deben ser dinamicos segun la cantidad seleccionada en el input de Productos/Precio

![image](https://user-images.githubusercontent.com/31671398/154111143-b4d9b17a-fb6f-4cd2-afab-0f7bada34a4f.png)

**Comment by emeery** [comment]
- SE REALIZA AJUSTES DE ISSUE

- Se ajusta el color de fondo transparente de el menu collapsable
- Se ajusta el tamano de fuente a 14px 
- Se agrega el contador a la tabla de productos/precio  
- Se ajustan estilos de menu colapsable

**Comment by jaasielmalagon** [comment]
Observaciones post revisión:
1. La opción seleccionada debe aparecer con background en color blanco, actualmente aparece en gris.
Maqueta: ![image](https://user-images.githubusercontent.com/31671398/154999878-c6a336fb-de6b-4681-a302-192a0de50a7a.png)
Código: 
![image](https://user-images.githubusercontent.com/31671398/155000256-7f617db4-7dc1-4bb8-92b4-b6f106527fcd.png)


2. Al hacer hover sobre un elemento de la lista debe de tener un background con color "secondary" (ya registrado en styles.css) 
Código actual: 
![image](https://user-images.githubusercontent.com/31671398/155000594-a1dbe961-583c-4c57-8bec-93106d036a34.png)
Maqueta: 
![image](https://user-images.githubusercontent.com/31671398/155000630-3c44dbdd-710b-40b3-8762-a11eb32c96c0.png)

3. Debe cambiar la tabla de precios a su derecha (no se corrigió en las observaciones anteriores REVISAR ATENTAMENTE)

4. El background (y otros estilos) están incorrectos, además debe llevar un scroll en Y (no en X) favor de revisar la maqueta.
Código actual: 
![image](https://user-images.githubusercontent.com/31671398/155001132-36996a7b-b354-4759-bd1d-9ec4075944e3.png)
Maqueta: 
![image](https://user-images.githubusercontent.com/31671398/155001258-35cdf7c3-3779-44b7-a336-a22157950909.png)

5. Los precios deben ser dinámicos según la cantidad seleccionada en el input de Productos/Precio
Código actual: 
![image](https://user-images.githubusercontent.com/31671398/155001536-ecf26c74-88a8-4674-869e-1707adaa3828.png)


FAVOR DE REVISAR Y CORREGIR PARA HOY, YA QUE ESTOS CAMBIOS DEBIERON ESTAR EN LA RESOLUCIÓN QUE SUBISTE Y NO LO ESTÁN, ADEMÁS URGE PORQUE ES LA ÚLTIMA SEMANA PARA AVANZAR.

**Comment by jaasielmalagon** [comment]
![image](https://user-images.githubusercontent.com/31671398/155203976-b2d54b2e-55a9-4579-b044-fa9458d2cce2.png)

Solo corregir estos detalles, lo demás ya está bien.

**Comment by emeery** [comment]
Se realizan las correciones

![imagen](https://user-images.githubusercontent.com/18725611/155623963-66eb1ef6-2fca-4c7b-9059-a4465dc8f839.png)

**Comment by jaasielmalagon** [comment]
Corrije tu estructura y que no haga -1
